### PR TITLE
Override storage fee

### LINKED ISSUE #2667: Optimize the payment logic of handling fees
The account balance is only $usdc and $aca
1. all $aca is used for `earning.Bonded`, the account Available balance is insufficient
2. use $usdc to swap on dex

This transaction will fail. The possible reason is that when operating evm token, a certain nativeToken is required for Reserved

Transfer 1 $aca to this address, and use`transactionPayment.withFeePath` to specify $usdc
This transaction was successful, verifying the conjecture:

1. $usdc can be used as handling fee
2. In the handling fee logic, the reserved nature of evm tokens is not taken into account.

image
image

### PR DESCRIPTION
**Pull request by wangjj9219**
resolve #2667

### CODE REVIEW

File: modules/transaction-payment/src/lib.rs [hunk 1]
```diff
@@ -269,6 +269,13 @@ pub mod module {
 	pub const RESERVE_ID: ReserveIdentifier = ReserveIdentifier::TransactionPayment;
 	pub const DEPOSIT_ID: ReserveIdentifier = ReserveIdentifier::TransactionPaymentDeposit;
 
+	#[derive(Encode, Decode, Clone, PartialEq, RuntimeDebug, TypeInfo)]
+	pub enum ChargeFeeWay {
+		FeeCurrency(CurrencyId),
+		FeePath(Vec<CurrencyId>),
+		FeeAggregatedPath(Vec<AggregatedSwapPath<CurrencyId>>),
```
Comment (xlc) [inline modules/transaction-payment/src/lib.rs:276]: I think we can merge FeePath into FeeAggregatedPath?

File: modules/transaction-payment/src/lib.rs [hunk 2]
```diff
@@ -269,6 +269,13 @@ pub mod module {
 	pub const RESERVE_ID: ReserveIdentifier = ReserveIdentifier::TransactionPayment;
 	pub const DEPOSIT_ID: ReserveIdentifier = ReserveIdentifier::TransactionPaymentDeposit;
 
+	#[derive(Encode, Decode, Clone, PartialEq, RuntimeDebug, TypeInfo)]
+	pub enum ChargeFeeWay {
```
Comment (xlc) [inline modules/transaction-payment/src/lib.rs:273]:
```suggestion
	pub enum ChargeFeeMethod{
```

File: modules/transaction-payment/src/tests.rs [hunk 3]
```diff
@@ -2176,34 +2210,41 @@ fn with_fee_call_validation_works() {
 
 			// with_fee_aggregated_path
 			let aggregated_path = vec![AggregatedSwapPath::Dex(vec![DOT, AUSD])];
-			assert_noop!(
+			assert_eq!(
```
Comment (xlc) [inline modules/transaction-payment/src/tests.rs:2213]: why this is changed?

Comment (wangjj9219) [reply modules/transaction-payment/src/tests.rs]: assert_noop  will throw a weird error: 
```
thread 'tests::with_fee_call_validation_works' panicked at modules/transaction-payment/src/tests.rs:2160:17:
assertion `left == right` failed: storage has been mutated
  left: [249, 149, 156, 205, 57, 147, 186, 208, 127, 112, 133, 173, 132, 93, 217, 62, 1, 173, 15, 252, 168, 86, 18, 7, 12, 133, 122, 249, 37, 36, 86, 78]
 right: [160, 125, 240, 154, 41, 126, 157, 145, 195, 135, 16, 84, 79, 200, 239, 206, 92, 159, 44, 8, 146, 97, 145, 12, 155, 52, 4, 30, 206, 186, 149, 211]
```

But use `assert_eq` shows it is `Err(TransactionValidityError::Invalid(InvalidTransaction::Payment))` actually.

Failed `ensure_can_charge_fee_with_call` may also set `OverrideChargeFeeMethod`, which may affects the judgment of `assert_noop`: https://github.com/paritytech/polkadot-sdk/blob/64d52f225e127575b51ab7fdf677783f5cd497f4/substrate/frame/support/src/lib.rs#L680-L693

I specific `ensure_can_charge_fee_with_call` to transactional, `assert_noop` works again.

Comment (xlc) [reply modules/transaction-payment/src/tests.rs]: yeah the error means the storage is changed

File: modules/transaction-payment/src/lib.rs [hunk 4]
```diff
@@ -855,68 +913,55 @@ where
...
 						&& fee_swap_path.first() != Some(&T::NativeCurrencyId::get())
 						&& fee_swap_path.last() == Some(&T::NativeCurrencyId::get()),
 					Error::<T>::InvalidSwapPath
 				);
+
+				let fee_aggregated_path: Vec<AggregatedSwapPath<CurrencyId>> =
+					vec![AggregatedSwapPath::<CurrencyId>::Dex(fee_swap_path.clone())];
+
+				// put in storage after check
+				OverrideChargeFeeMethod::<T>::put(ChargeFeeMethod::FeeAggregatedPath(fee_aggregated_path.clone()));
```
Comment (xlc) [inline modules/transaction-payment/src/lib.rs:929]:
```suggestion
				OverrideChargeFeeMethod::<T>::put(ChargeFeeMethod::FeeAggregatedPath(&fee_aggregated_path));
```

File: modules/transaction-payment/src/lib.rs [hunk 5]
```diff
@@ -855,68 +913,55 @@ where
...
-								&& fee_swap_path.first() != Some(&T::NativeCurrencyId::get())
+							fee_swap_path.len() <= T::TradingPathLimit::get() as usize
+								&& fee_swap_path.len() > 1 && fee_swap_path.first() != Some(&T::NativeCurrencyId::get())
 								&& fee_swap_path.last() == Some(&T::NativeCurrencyId::get()),
 							Error::<T>::InvalidSwapPath
 						);
+
+						// put in storage after check
+						OverrideChargeFeeMethod::<T>::put(ChargeFeeMethod::FeeAggregatedPath(
+							fee_aggregated_path.clone(),
```
Comment (xlc) [inline modules/transaction-payment/src/lib.rs:950]:
```suggestion
							&fee_aggregated_path,
```

**Review by xlc — APPROVED** [review]

File: modules/support/src/dex.rs [hunk 6]
```diff
@@ -179,11 +179,17 @@ where
 
 	// Dex not support aggregated swap.
```
Comment (zjb0807) [inline modules/support/src/dex.rs:180]:
```suggestion
```

File: modules/transaction-payment/src/lib.rs [hunk 7]
```diff
@@ -842,11 +856,55 @@ where
...
+		fee_currency_id: CurrencyId,
+	) -> Result<(T::AccountId, Balance), DispatchError> {
+		let alternative_fee_surplus = T::AlternativeFeeSurplus::get().mul_ceil(fee);
+		let custom_fee_surplus = T::CustomFeeSurplus::get().mul_ceil(fee);
+
+		let (fee_amount, fee_surplus) = if T::DefaultFeeTokens::get().contains(&fee_currency_id) {
+			(fee.saturating_add(alternative_fee_surplus), alternative_fee_surplus)
+		} else {
+			(fee.saturating_add(custom_fee_surplus), custom_fee_surplus)
+		};
```
Comment (zjb0807) [inline modules/transaction-payment/src/lib.rs:885]:
```suggestion
		let (fee_amount, fee_surplus) = if T::DefaultFeeTokens::get().contains(&fee_currency_id) {
			let alternative_fee_surplus = T::AlternativeFeeSurplus::get().mul_ceil(fee);
			(fee.saturating_add(alternative_fee_surplus), alternative_fee_surplus)
		} else {
			let custom_fee_surplus = T::CustomFeeSurplus::get().mul_ceil(fee);
			(fee.saturating_add(custom_fee_surplus), custom_fee_surplus)
		};
```

File: modules/transaction-payment/src/lib.rs [hunk 8]
```diff
@@ -944,6 +989,22 @@ where
...
+				Some(ChargeFeeMethod::FeeCurrency(fee_currency_id)) => {
+					if let Ok((_, surplus)) = Self::charge_fee_currency(who, amount, fee_currency_id) {
+						return Ok(surplus);
+					}
+				}
+				Some(ChargeFeeMethod::FeeAggregatedPath(fee_aggregated_path)) => {
+					if let Ok((_, surplus)) = Self::charge_fee_aggregated_path(who, amount, &fee_aggregated_path) {
+						return Ok(surplus);
+					}
+				}
```
Comment (zjb0807) [inline modules/transaction-payment/src/lib.rs:1004]: here should return an error instead of trying other tokens.
@xlc what do you think?

File: modules/transaction-payment/src/lib.rs (hunk 4 above)
Comment (wangjj9219) [reply modules/transaction-payment/src/lib.rs]: `fee_aggregated_path` is reference here, change it to `fee_aggregated_path.to_vec()` according to complier suggest

File: modules/transaction-payment/src/lib.rs (hunk 8 above)
Comment (xlc) [reply modules/transaction-payment/src/lib.rs:1003]: yeah I agree

**Review by zjb0807 — DISMISSED** [review]

File: runtime/integration-tests/src/stable_asset.rs [hunk 9]
```diff
@@ -588,6 +588,8 @@ fn three_usd_pool_works() {
 			assert_aggregated_dex_event(usdc, with_fee_currency_call(usdc), None);
 			assert_aggregated_dex_event(usdt, with_fee_currency_call(usdt), None);
 
+			//assert_eq!(System::events(), vec![]);
```
Comment (xlc) [inline runtime/integration-tests/src/stable_asset.rs:591]:
```suggestion
```

**Review by xlc — DISMISSED** [review]

**Review by xlc — DISMISSED** [review]

**Review by xlc — APPROVED** [review]
